---
- name: Configure Logstash repo
  copy:
    src: "logstash-yum-repo_{{ ansible_distribution_file_variety }}_{{ ansible_distribution_major_version }}"
    dest: /etc/yum.repos.d/logstash.repo
    mode: 0755
    owner: root
    group: root

- name: Install Logstash Dependencies
  yum:
    name: "{{ dependency_pkgs }}"
    state: present

- name: Install Logstash Package
  yum:
    name: logstash
    state: present

- name: Start Logstash on boot
  service:
    name: logstash
    enabled: yes
  notify:
    - start logstash
